networks:
  net:
    external: false

volumes:
  postgres-db:
    external: false

services:
  db:
    image: postgres:alpine
    env_file:
      - .env.db
    restart: unless-stopped
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=trust
    healthcheck:
      # Prueba de salud para el contenedor
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 2s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d # Scripts que se ejecutan solamente al iniciar por primera vez el servidor
      - ./datos:/datos
    networks:
      - net

  superset:
    image: apache/superset:4.0.0
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - 8088:8088
    depends_on:
      db:
        condition: service_healthy # Aguarda hasta que la base de datos este funcionando correctamente
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net